namespace Yuzu.Syntax;

public enum SyntaxKind : ushort
{
    Unknown = 0,
    Eof,
    // Trivia
    SingleLineCommentTrivia,
    DocCommentTrivia,
    MultiLineCommentTrivia,
    NewLineTrivia,
    WhitespaceTrivia,
    ConflictMarkerTrivia,
    NonTextFileMarkerTrivia,
    // Literals
    CharLiteral,
    StringLiteral,
    NumberLiteral,
    // Punctuation
    ExclamationToken,
    ExclamationEqualsToken,
    PercentToken,
    PercentEqualsToken,
    CaretToken,
    CaretEqualsToken,
    AmpersandToken,
    AmpersandEqualsToken,
    AmpersandAmpersandToken,
    AmpersandAmpersandEqualsToken,
    LParenToken,
    RParenToken,
    LBraceToken,
    RBraceToken,
    LBracketToken,
    RBracketToken,
    ColonToken,
    SemicolonToken,
    CommaToken,
    AtToken,
    TildeToken,
    SharpToken,
    DotToken,
    DotDotToken,
    LessThanToken,
    LessThanEqualsToken,
    LessThanLessThanToken,
    LessThanLessThanEqualsToken,
    GreaterThanToken,
    GreaterThanEqualsToken,
    GreaterThanGreaterThanToken,
    GreaterThanGreaterThanEqualsToken,
    EqualsToken,
    EqualsEqualsToken,
    EqualsGreaterThanToken, 
    PipeToken,
    PipeEqualsToken,
    PipePipeToken,
    PipePipeEqualsToken,
    QuestionToken,
    QuestionDotToken,
    QuestionQuestionToken,
    QuestionQuestionEqualsToken,
    PlusToken,
    PlusPlusToken,
    PlusEqualsToken,
    MinusToken,
    MinusMinusToken,
    MinusEqualsToken,
    StarToken,
    StarEqualsToken,
    SlashToken,
    SlashEqualsToken,
    // Identifier and Keywords
    Identifier,
    IfKeyword,
    ForKeyword,
    VarKeyword,
    ValKeyword,
    FunKeyword,
    ElseKeyword,
    PrintKeyword, // Temporary
    // Types (in Keywords)
    StringKeyword,
    CharKeyword,
    BoolKeyword,
    ByteKeyword,
    SByteKeyword,
    ShortKeyword,
    UShortKeyword,
    IntKeyword,
    UIntKeyword,
    LongKeyword,
    ULongKeyword,
    FloatKeyword,
    DoubleKeyword,
    VoidKeyword,
}
